name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: Tests PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: [8.3]
        experimental: [false]
        include:
          - php: 8.3
            analysis: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v1

      - name: Coding standards
        if: matrix.analysis
        run: composer run phpcs

      - name: Coverage
        run: composer run coverage

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.coverage
          publish_branch: gh-pages

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./.coverage